name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      ENV_BUILD: GH

    steps:
    - uses: actions/checkout@v3
    - name: Check if the fmstd.h is updated
      run: ./scripts/check_header.sh
    - name: Install debug dependencies
      run: sudo apt-get update && sudo apt-get install -y clang clang-format valgrind cppcheck 
    - name: Checks the format of src/*
      run: clang-format -style=file -dry-run -Werror src/*
    - name: Check the format of the header
      run: clang-format -style=file --Werror -dry-run fmstd.h
    - name: Build tests
      run: ./scripts/build_tests.sh
    - name: Run tests
      run: ./scripts/run_tests.sh
    - name: Build and run example
      run: ./scripts/build_run_example.sh

